### ISSUE TITLE
Prudent can't find `ledger` on M1 macs

### ISSUE THREAD

**Issue by sbibauw** [PrudentMe/main#13]
On ARM-based M1 Macs (late 2020), Prudent can't find Ledger-cli executable, even when it is properly installed via Homebrew. On these, `brew install ledger` installs it in `/opt/homebrew/bin/ledger` rather than `/usr/local/bin/ledger`.

I suppose Prudent is looking for `/usr/local/bin/ledger` rather than just any `ledger` executable in the `PATH`, which would be the correct procedure I guess. Otherwise, allow the user to define in Settings where `ledger` is located...

**Comment by vitoc** [comment]
Thanks @sbibauw Added ```/opt/homebrew/bin/ledger``` to the list of paths that is checked for Ledger-cli executable. This is in Release 28. Will add more options to configure this to the backlog as well :)

**Comment by sbibauw** [comment]
@vitoc Not sure why, but with release 28 I get this error message:

     Command failed: "/opt/boxen/homebrew/ledger" -f my.journal

Why is it searching in `/opt/boxen/...` ?

**Comment by vitoc** [comment]
Sorry @sbibauw made a mistake with the path, fixed in R29: https://github.com/PrudentMe/main/releases/tag/29
