### ISSUE TITLE
Prudent (Mac) r14: version number hasn't changed since release 12?

### ISSUE THREAD

**Issue by suschizu** [PrudentMe/main#3]
Hello @vitoc! 
I'm not sure if this is intentional - but the version number of the latest release is the same as in release 12
![image](https://user-images.githubusercontent.com/16004333/68088723-18edd280-fe62-11e9-9709-792167a6b347.png)

**Comment by vitoc** [comment]
Hello @suschizu Thanks! Sorry for missing this earlier. The version should now be updated:

![image](https://user-images.githubusercontent.com/558813/72394040-c2f5af00-376f-11ea-8eb9-a3dce91c7a9b.png)
