### ISSUE TITLE
Error on Windows if txt file is not on C:

### ISSUE THREAD

**Issue by jnsbdev** [PrudentMe/main#6]
If i save my txt file on a second hard disk, an error message appears:

> Error: File to include was not found:
> "C:/Users\Username\AppData\Local\Prudent\User Data\Data\cache\D:/Untitled.txt

It looks like the paths are not separated.

**Comment by vitoc** [comment]
Thanks! This is fixed in Release 24 (you'll need to download Release 24 to get this fix).
