### ISSUE TITLE
“Prudent” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by producercoder** [PrudentMe/main#9]
I'm on MacOS Catalina - 10.15.7 and tried installing and running Prudent today.

The error on launch is:
“Prudent” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

**Comment by vitoc** [comment]
Fixed! macOS version of Release 25 is now notarized. Please download again: https://github.com/PrudentMe/main/releases/download/25/Prudent.zip
